### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by imgulali** [Rorailer/Movies_to_torrent#1]
Unable to find requirements.txt to install the required dependencies!
<img width="697" alt="shot" src="https://github.com/Rorailer/Movies_to_torrent/assets/110970153/5427ac6f-7f03-42cc-afdd-7e708dee4aa4">

**Comment by imgulali** [comment]
Not a python guy. Found that you had it solved in the Readme ;)

**Comment by Rorailer** [comment]
Fixed. Added a requirements.txt file.

**Comment by imgulali** [comment]
Thanks!
